[DSME] Use wheel group as priveleged
sailfishos/dsme pull request #2
Opened 2021-09-28 12:34 UTC by neochapay

In nemo we don't have privileged user but we can use wheel group for detect privileged users

2021-10-04 10:16 UTC, spiiroin requested changes

2021-10-04 10:16 UTC, spiiroin commented on configure.ac
> +# Wheell is priveleged
typos: '"Wheell', "priveleged"

("priveleged" appears in couple other places too)

2021-10-04 10:16 UTC, spiiroin commented on dsme/utility.c
> +                   is_privileged = true;
All groups except "wheel" are privileged? Should be `if( strcmp() == 0 )`?

Also, once a match is found, one might as well break out of the loop.

2021-10-04 10:16 UTC, spiiroin commented on configure.ac
> +    [use wheel group users as priveleged])])
I'm wondering if that explanation could be clarified a bit?

Say, something like "Users in wheel group are considered privileged", or maybe "Only users..." depending on whether root user that does not belong to wheel group is intentionally excluded or not.

2021-10-04 14:02 UTC, spiiroin requested changes

2021-10-04 14:02 UTC, spiiroin commented on configure.ac
> +AM_CONDITIONAL([WANT_USEWHEEL], [test x$enable-usewheel != xno])
Looks like DSME_USEWHEEL ends up always defined regardless of configure options - which is not ok.

After taking a brief AC_ARG_ENABLE refresher... AFAICT enabling "disabled-by-default" config item (like this usewheel here) should use "x$topic" == xyes" type tests.

(On a quick glance a lot of the other already existing config options have similar issues, but fixing those falls outside the context of this pull req)

2021-10-04 15:28 UTC, PureTryOut commented
Depending on the distro, it might not actually be "wheel" that has "sudo rights". I've seen other group names before, I think even in plain Debian (but I can't recall right now). Would it maybe be possible to parse `/etc/sudoers` to verify which group is privileged (if any at all)?  Then again, you maybe don't want to depend on `sudo` and `/etc/sudoers` being available, people could want or have `doas` instead. Is there not some other way to check if the user has the required rights? Or maybe just make the group name configurable at compile time (and default to `wheel`), that's probably the easiest.

2021-10-05 07:02 UTC, spiiroin commented
Ad-hoc test: building sans --enable-usewheel -> uses root/privileged as before (= what sailfish needs); building with  --enable-usewheel -> only users added to the wheel group are privileged = matches what I understand the intent of this pr to be -> LGTM

> Or maybe just make the group name configurable at compile time (and default to `wheel`), that's probably the easiest.

Assuming that: 1) there is concrete need for wheel group use (= a problem that this pr solves), 2) apparently at the moment there is no known and well defined need for more degrees of freedom, and 3) making the group name configurable can be done later on too -> I would not place burden of potentially unnecessary future proofing on this pull req... So I'd leave it up to: @neochapay, do you want to implement also such group name config option? Or should we just merge this as it is now?

2021-10-05 08:47 UTC, neochapay commented
@spiiroin merge as is. If @PureTryOut need some other thinks it make own MR :)

2021-10-05 11:15 UTC, PureTryOut commented
I don't need anything personally, my system (postmarketOS/Alpine Linux) also uses the wheel group so I'm fine there. I was just thinking further and "what if other systems would use this, what problems might they encounter"? Trying to improve the whole thing  for everyone basically, and just thinking out loud :wink:

2021-10-06 08:44 UTC, spiiroin approved these changes

2021-10-06 08:44 UTC, merged

2021-10-06 09:32 UTC, spiiroin commented
Included in dsme 0.84.0 tag